version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 712884342706.dkr.ecr.ap-south-1.amazonaws.com
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t aapooncontactssecuredrepo-qa:latest .
  build:
    commands:
      - echo Build started on `date`
      - echo Tagging the Docker image...
      - docker tag aapooncontactssecuredrepo-qa:latest 712884342706.dkr.ecr.ap-south-1.amazonaws.com/aapooncontactssecuredrepo-qa:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 712884342706.dkr.ecr.ap-south-1.amazonaws.com/aapooncontactssecuredrepo-qa:latest
      - echo Writing image definitions file...
      - printf '[{"name":"aapooncontactssecuredrepo-qa","imageUri":"712884342706.dkr.ecr.ap-south-1.amazonaws.com/aapooncontactssecuredrepo-qa:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
